"""Initial schema

Revision ID: 570000c54a9c
Revises: 
Create Date: 2026-07-30 17:09:13.901219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570000c54a9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject', 'name', name='uq_concept_subject_name')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_subject'), ['subject'], unique=False)

    op.create_table('eligible_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_number', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('section', sa.String(length=16), nullable=True),
    sa.Column('claimed', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligible_students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligible_students_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_eligible_students_register_number'), ['register_number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_number', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('section', sa.String(length=16), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('account_status', sa.String(length=16), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_register_number'), ['register_number'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('registration_start', sa.DateTime(), nullable=False),
    sa.Column('registration_end', sa.DateTime(), nullable=False),
    sa.Column('exam_start', sa.DateTime(), nullable=False),
    sa.Column('exam_end', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('starting_level', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('allow_late_start', sa.Boolean(), nullable=False),
    sa.Column('show_result_immediately', sa.Boolean(), nullable=False),
    sa.Column('exam_kind', sa.String(length=16), nullable=False),
    sa.Column('show_inline_feedback', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('study_group', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_exam_kind'), ['exam_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_study_group'), ['study_group'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('current_sequence', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_answered', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('credited_score', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('submission_reason', sa.String(length=24), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'user_id', name='uq_attempt_exam_user')
    )
    op.create_table('exam_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'concept_id', 'level', name='uq_blueprint_cell')
    )
    op.create_table('exam_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'concept_id', name='uq_exam_concept')
    )
    with op.batch_alter_table('exam_concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_concepts_exam_id'), ['exam_id'], unique=False)

    op.create_table('exam_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'user_id', name='uq_registration_exam_user')
    )
    op.create_table('project_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('source_filenames', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('concepts_json', sa.Text(), nullable=True),
    sa.Column('technologies_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generation_source', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('analysed_at', sa.DateTime(), nullable=True),
    sa.Column('questions_generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exam_id', name='uq_submission_user_exam')
    )
    with op.batch_alter_table('project_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_submissions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_submissions_user_id'), ['user_id'], unique=False)

    op.create_table('integrity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('event_value', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrity_events_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=16), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=True),
    sa.Column('option_b', sa.Text(), nullable=True),
    sa.Column('option_c', sa.Text(), nullable=True),
    sa.Column('option_d', sa.Text(), nullable=True),
    sa.Column('correct_option', sa.String(length=1), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('breakdown_a', sa.Text(), nullable=True),
    sa.Column('breakdown_b', sa.Text(), nullable=True),
    sa.Column('breakdown_c', sa.Text(), nullable=True),
    sa.Column('breakdown_d', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('generation_method', sa.String(length=24), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_submission_id'), ['submission_id'], unique=False)

    op.create_table('study_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('concept_name', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('where_used', sa.Text(), nullable=True),
    sa.Column('recommended_answer', sa.Text(), nullable=True),
    sa.Column('misconception', sa.Text(), nullable=True),
    sa.Column('revision_points_json', sa.Text(), nullable=True),
    sa.Column('retrieved_context', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'concept_name', name='uq_card_submission_concept')
    )
    with op.batch_alter_table('study_cards', schema=None) as batch_op:
        batch_op.create_index('ix_card_subject_concept', ['subject', 'concept_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_cards_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_cards_submission_id'), ['submission_id'], unique=False)

    op.create_table('assigned_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('displayed_option_order', sa.String(length=16), nullable=False),
    sa.Column('assigned_level', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('is_remedial', sa.Boolean(), nullable=False),
    sa.Column('remedial_for_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['remedial_for_id'], ['assigned_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_assigned_once'),
    sa.UniqueConstraint('attempt_id', 'sequence_number', name='uq_assigned_sequence')
    )
    with op.batch_alter_table('assigned_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assigned_questions_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('assigned_question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=True),
    sa.Column('descriptive_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('response_time_seconds', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('finalised', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_question_id'], ['assigned_questions.id'], ),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assigned_question_id', name='uq_response_per_assigned_question')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_attempt_id'), ['attempt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_attempt_id'))

    op.drop_table('responses')
    with op.batch_alter_table('assigned_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assigned_questions_attempt_id'))

    op.drop_table('assigned_questions')
    with op.batch_alter_table('study_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_cards_submission_id'))
        batch_op.drop_index(batch_op.f('ix_study_cards_subject'))
        batch_op.drop_index('ix_card_subject_concept')

    op.drop_table('study_cards')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_submission_id'))
        batch_op.drop_index(batch_op.f('ix_questions_subject'))
        batch_op.drop_index(batch_op.f('ix_questions_review_status'))
        batch_op.drop_index(batch_op.f('ix_questions_level'))
        batch_op.drop_index(batch_op.f('ix_questions_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_questions_concept_id'))

    op.drop_table('questions')
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrity_events_attempt_id'))

    op.drop_table('integrity_events')
    with op.batch_alter_table('project_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_submissions_exam_id'))

    op.drop_table('project_submissions')
    op.drop_table('exam_registrations')
    with op.batch_alter_table('exam_concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_concepts_exam_id'))

    op.drop_table('exam_concepts')
    op.drop_table('exam_blueprints')
    op.drop_table('attempts')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_study_group'))
        batch_op.drop_index(batch_op.f('ix_exams_exam_kind'))

    op.drop_table('exams')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_register_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('eligible_students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligible_students_register_number'))
        batch_op.drop_index(batch_op.f('ix_eligible_students_email'))

    op.drop_table('eligible_students')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_subject'))

    op.drop_table('concepts')
    # ### end Alembic commands ###
