"""
subject_loader.py
-----------------
Loads backend college notes that ground Subject Viva.

DBMS is grounded by subject_materials/dbms_notes.txt. OS ships with autogenerated
notes (below) so it works out of the box; real OS notes can be dropped into
subject_materials/os_notes.txt later and will be preferred automatically.
"""

import os

from app.core.text_processing import normalize_text

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
MATERIALS_DIR = os.environ.get(
    "SUBJECT_MATERIALS_DIR", os.path.join(_PROJECT_ROOT, "subject_materials")
)

# Autogenerated OS notes used if no os_notes.txt is present.
_OS_AUTONOTES = """OPERATING SYSTEMS - AUTOGENERATED NOTES

PROCESSES AND THREADS
A process is a program in execution with its own address space. The Process
Control Block (PCB) stores process state, program counter, registers, and
scheduling info. Processes move between new, ready, running, waiting, and
terminated states. A thread is a lightweight unit of execution within a process;
threads share the process address space. Context switching saves one process
state and loads another, which has overhead.

CPU SCHEDULING
CPU scheduling selects which ready process runs next to maximize utilization,
throughput, and fairness. FCFS runs processes in arrival order without preemption.
SJF picks the shortest burst to minimize average waiting time. Round Robin gives
each process a fixed time quantum with preemption. Priority scheduling runs the
highest-priority process, and a multilevel feedback queue adapts priorities.

VIRTUAL MEMORY AND PAGING
Virtual memory lets a process use more address space than physical RAM. Paging
divides logical memory into fixed-size pages and physical memory into equal frames.
The page table maps virtual pages to physical frames. The Translation Lookaside
Buffer (TLB) caches recent mappings. A page fault occurs when a needed page is not
in memory and must be loaded from disk. Excessive paging causes thrashing, where
the system spends most time swapping instead of executing.

DEADLOCKS
A deadlock occurs when processes wait forever for resources held by each other.
The four Coffman conditions are mutual exclusion, hold and wait, no preemption, and
circular wait. Deadlocks can be prevented, avoided (Banker's algorithm), detected,
or ignored. Breaking any one condition prevents deadlock.

PROCESS SYNCHRONIZATION
Synchronization coordinates concurrent access to shared resources. The critical
section is code that accesses shared data. A race condition occurs when the result
depends on timing. Semaphores and mutexes enforce mutual exclusion so only one
process enters the critical section at a time.

FILE SYSTEMS
A file system organizes data on storage into files and directories. An inode
stores file metadata. Files can use contiguous, linked, or indexed allocation.
Directories map file names to their storage locations.
"""


def _read_file(path: str) -> str:
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            return f.read()
    except OSError:
        return ""


def load_subject_notes(subject: str) -> str:
    """Return normalized backend notes for a subject."""
    subject = subject.upper()

    if subject == "DBMS":
        path = os.path.join(MATERIALS_DIR, "dbms_notes.txt")
        raw = _read_file(path)
        return normalize_text(raw)

    if subject == "OS":
        path = os.path.join(MATERIALS_DIR, "os_notes.txt")
        raw = _read_file(path)
        if not raw.strip():
            raw = _OS_AUTONOTES
        return normalize_text(raw)

    return ""


def has_backend_notes(subject: str) -> bool:
    return bool(load_subject_notes(subject).strip())
